[package]
name = "reth-pulsechain-forks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "PulseChain hardfork definitions and chain specs for reth."

[lints]
workspace = true

[dependencies]
# reth
reth-ethereum-forks = { workspace = true, default-features = false }
reth-chainspec.workspace = true
reth-network-peers = { workspace = true, default-features = false }

# alloy
alloy-eips = { workspace = true, default-features = false }
alloy-primitives.workspace = true

[features]
default = ["std"]
std = [
    "reth-chainspec/std",
    "reth-ethereum-forks/std",
    "alloy-primitives/std",
]
